### PR TITLE
Sai test

### PR DESCRIPTION
**Pull request by v-sambati**
Updated Analytics Admin Permissions PDF

### CODE REVIEW

**Comment by PRMerger15** [comment]
@v-sambati : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nikotha

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added or Deleted File(s) | This PR contains added or deleted file(s).
 Unapproved file extension(s) |  This PR contains file types that are not supported in the repo. The only supported file types are jpg, gif, png, json, svg and md.
 Image File | This PR contains an image file(s).

**Review by nikotha — COMMENTED** [review]
Are both the jpg and pdf file required?

**Comment by v-sambati** [comment]
> Are both the jpg and pdf file required?

Both files not needed, actually testing on VS code on how we can upload PDF and image, looks like for PDF upload I did a work around by editing in Github rather than VS code, and for images we can link then directly in VS code

**Comment by PRMerger10** [comment]
@v-sambati : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nikotha

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added or Deleted File(s) | This PR contains added or deleted file(s).
 Unapproved file extension(s) |  This PR contains file types that are not supported in the repo. The only supported file types are jpg, gif, png, json, svg and md.
 Image File | This PR contains an image file(s).

**Pull request merged**
