### PR TITLE
Org Admin and global content

### PR DESCRIPTION
**Pull request by abdulzabbarshaik**
Org Admin and global content documentation additions

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Changed Files | This PR contains more than 10 changed files.
 Image File | This PR added or updated an image file(s).

**Comment by PRMerger15** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Changed Files | This PR contains more than 10 changed files.
 Image File | This PR added or updated an image file(s).

**Comment by PRMerger9** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Changed Files | This PR contains more than 10 changed files.
 Image File | This PR added or updated an image file(s).

**Comment by PRMerger20** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@abdulzabbarshaik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Image File | This PR added or updated an image file(s).

**Pull request merged**
