### PR TITLE
Live

### PR DESCRIPTION
**Pull request by v-sambati**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@v-sambati : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Unapproved file extension(s) |  This PR contains file types that are not supported in the repo. The only supported file types are jpg, gif, png, json, svg and md.

**Comment by v-sambati** [comment]
update AAD script link as public access to Sangam blob is blocked

**Comment by PRMerger8** [comment]
@v-sambati : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
